### ISSUE TITLE
how to run server in your website?

### ISSUE THREAD

**Issue by AnonHexo** [TrAyZeN/youtube-downloader#3]
how could i run this downloader in my website instead of localhost???

**Comment by TrAyZeN** [comment]
Hello, you could could make the server listen on `0.0.0.0` instead of `localhost` by modifying the call to `server.listen` in `src/bin/www.js` or you could use a reverse proxy like [Nginx](https://nginx.org/en/) or [Caddy](https://caddyserver.com/v2) to expose your local application.

**Comment by AnonHexo** [comment]
ok thx
