### ISSUE TITLE
Issue

### ISSUE THREAD

**Issue by facuquilmes123** [TrAyZeN/youtube-downloader#45]
Hi !! Firt, Thanks a lot for share this proyect.
I have this at deploying in heroku:

remote:        Running build (yarn)
remote:        yarn run v1.22.17
remote:        $ yarn --cwd frontend build && tsc --project ./ && mkdir -p ./build/frontend && cp -r ./frontend/public ./build/frontend/public
remote:        $ rollup -c
remote: /bin/sh: 1: rollup: not found
remote: error Command failed with exit code 127.
remote:        info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.
remote: error Command failed with exit code 127.
remote:        info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.
remote:
remote: -----> Build failed
remote:
remote:        We're sorry this build is failing! You can troubleshoot common issues here:
remote:        https://devcenter.heroku.com/articles/troubleshooting-node-deploys
remote:
remote:        Some possible problems:
remote:
remote:        - Node version not specified in package.json
remote:          https://devcenter.heroku.com/articles/nodejs-support#specifying-a-node-js-version
remote:
remote:        Love,
remote:        Heroku
remote:
remote:  !     Push rejected, failed to compile Node.js app.
remote:
remote:  !     Push failed

**Comment by TrAyZeN** [comment]
Hi,

Sorry for the delay. It should be fixed by 6f6863c1512bb3e51ac687553e81c4a5cee03ba4.
